<script src="<?= base_url('assets/template/js/app.min.js'); ?>"></script>
<script src="<?= base_url('assets/template/bundles/datatables/datatables.min.js'); ?>"></script>
<script src="<?= base_url('assets/template/bundles/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js'); ?>"></script>
<script src="<?= base_url('assets/template/bundles/jquery-ui/jquery-ui.min.js'); ?>"></script>
<script src="<?= base_url('assets/template/js/page/datatables.js'); ?>"></script>
<script src="<?= base_url('assets/template/bundles/select2/dist/js/select2.full.min.js'); ?>"></script>
<script src="<?= base_url('assets/template/bundles/sweetalert/sweetalert.min.js'); ?>"></script>
<script src="<?= base_url('assets/template/js/page/sweetalert2.min.js'); ?>"></script>
<script src="<?= base_url('assets/template/js/scripts.js'); ?>"></script>
<script src="<?= base_url('assets/template/js/custom.js'); ?>"></script>
<script src="<?= base_url('assets/template/bundles/izitoast/js/iziToast.min.js'); ?>"></script>
<script src="<?= base_url('assets/template/js/page/toastr.js'); ?>"></script>
<script src="<?= base_url('application/views/inventory/purchasing/purchaseorder/domRender.js') ?>"></script>
<script src="<?= base_url('application/views/inventory/purchasing/purchaseorder/domElement.js'); ?>"></script>
<script src="<?= base_url('application/views/inventory/purchasing/purchaseorder/domDatatable.js'); ?>"></script>
<script src="<?= base_url('application/views/inventory/purchasing/purchaseorder/domInputData.js'); ?>"></script>
<script src="<?= base_url('application/views/inventory/purchasing/purchaseorder/domRouting.js'); ?>"></script>